### PR TITLE
support for ADDON_PURECFLAGS variable for Pure C (not C++) flag

### PR DESCRIPTION
**Pull request by danomatika**
Added support to parse a ADDON_PURECFLAGS variable which sets C flags (not CXX_FLAGS). This is mainly needed for Xcode and it sets the Other C Flags so defines can be set when compiling pure C sources. I also added support to Visual Studio projects where it simply adds them to the same line as the C++ flags (`\cl` I believe). Tested and working on Xcode, so now generated ofxPd projects can actually build. I'll add support for this flag to the Makefiles next.

Also fixed some wrong variables and prints which looked like they were left over from copy/pasting and not updated.

### CODE REVIEW

**Comment by danomatika** [comment]
Ping @bakercp

**Comment by arturoc** [comment]
i think it would be much more standard to call this ADDONS_CFLAGS and the current one ADDONS_CXXFLAGS. which is the standard in most build systems. i don't think there's many addon_config.mk files yet so it shouldn't be too problematic to fix it. also we could make ADDONS_CXXFLAGS = ADDONS_CFLAGS unless it's defined which should make it perfectly compatible with old files

**Comment by danomatika** [comment]
I know it's more standard. I chose a different name to make sure not to break anything. If there is a decision to go to the standard naming, I can change it.

**Comment by bakercp** [comment]
+1 on standard naming.

**Comment by danomatika** [comment]
Following the current naming (aka ADDON_C_SOURCES & ADDON_CPP_SOURCES), shouldn't we use ADDON_CPPFLAGS?

**Comment by arturoc** [comment]
CPPFLAGS sounds good too. as i said we can make both the PG and the makefile make CPPFLAGS=CFLAGS by default, then when parsing the config file if CPPFLAGS it's defined it'll override the value

with that old files shouldn't break

it's done like that for all other variables except the default value is empty but let me know if you need help with it

**Comment by danomatika** [comment]
Ok, I'm updating it now.

**Comment by danomatika** [comment]
Also: Xcode copies OTHER_CFLAGS into OTHER_CPLUSPLUSFLAGS by default.

**Comment by danomatika** [comment]
Ok, I updated it to ADDON_CFLASG & ADDON_CPPFLAGS. Tested in Xcode for OS X & iOS.

I also fixed the .mm issue with libs. There is an extension check there that was only including .h, .hpp, .c, .cc, .cpp files. I added support for .cxx (another .cpp alternative), .m, and .mm. Not ofxMidi iOS projects include PGMidi .m files correctly.

**Comment by danomatika** [comment]
I'll add the fix for the Core addon makefile. I hope this can be merged and included in the 0.9.0 release.

**Comment by danomatika** [comment]
The makefile var names are now updated in my core OF PR. This is basically done.

**Comment by arturoc** [comment]
thanks!

**Pull request merged**
